declare const classNames: {
  readonly titleFour: "titleFour";
  readonly titleOne: "titleOne";
  readonly titleTwo: "titleTwo";
  readonly titleThree: "titleThree";
  readonly contant: "contant";
  readonly title: "title";
  readonly svg: "svg";
  readonly selectAndInput: "selectAndInput";
  readonly highlightedText: "highlightedText";
  readonly sidebar: "sidebar";
  readonly hamburger: "hamburger";
  readonly menu: "menu";
  readonly menuActive: "menuActive";
  readonly menuContent: "menuContent";
  readonly link: "link";
  readonly chatPanel: "chatPanel";
  readonly chatOpen: "chatOpen";
  readonly chat: "chat";
};
export = classNames;
